# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IYlqo1UPbWRdHO8ce65haNDGGwajii52
"""

import re # !pip install regex
email_condition = "^[a-z]+[\._]?[a-z 0-9]+[@]\w+[.]\w{2,3}$"
user_email = input("Enter your mail id: ")
if re.search(email_condition, user_email):
  print("Right email")
else:
  print("Wrong email")